Desktop/helen/Program/django_practice/mypage/blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
	path(r'', views.post_list, name='post_list'),
	path(r'tag/<tag_slug>',views.post_list,name='post_list_by_tag'),
	# path(r'',views.PostListView.as_view(),name='post_list'),
	path(r'<int:year>/<int:month>/<int:day>/<post>/',
        views.post_detail,
        name='post_detail'),
	# path(r'<int:post_id>/share/',views.post_share,name='post_share'),
]

Desktop/helen/Program/django_practice/mypage/mypage/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path(r'blog/',include(('blog.urls',"blog"),namespace="blog")),
    # path(r'blog/',include('blog.urls')),
    path('admin/', admin.site.urls),
]

Desktop/helen/Program/django_practice/mypage/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager #添加標籤用

# Create your models here.

class PublishedManager(models.Manager):
	def get_query(self):
		return super(PublishedManager,self).get_queryset().filter(status='published')

class  Post(models.Model):
	"""docstring for  Posr"""
	STATUS_CHOICES=(
			('draft','Draft'),
			('published','Published')
	)
	title = models.CharField(max_length=250) 
	slug = models.SlugField(max_length=250,unique_for_date='publish') 
	author = models.ForeignKey(User,related_name='blog_posts',on_delete=models.CASCADE)
	body = models.TextField()
	publish = models.DateTimeField(default=timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now = True)
	status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
	objects = models.Manager()
	published = PublishedManager()
	tags = TaggableManager()
	class Meta:
		ordering = ('-publish',)
	def get_absolute_url(self):
		   #reverse 允许你通过它们的名字和可选的参数来构建URLS
		   # blog:post_detail
		return reverse('blog:post_detail',
					args=[self.publish.year,
						  self.publish.strftime('%m'),
						  #用strftime保證個位數前面會帶上0
						  self.publish.strftime('%d'),
						  self.slug]) 
	def __str__(self):
		return self.title
	def get_home_page(self):
		return reverse('blog:post_list')

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments',on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ('created',)
        
    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

Desktop/helen/Program/django_practice/mypage/blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
	name = forms.CharField(max_length=25) #<input type=“text”>
	email = forms.EmailField()
	to = forms.EmailField()
	comments = forms.CharField(required=False,widget=forms.Textarea)
	#<textarea></textarea>

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('name','email','body')

Desktop/helen/Program/django_practice/mypage/blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post
#翻頁
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.views.generic import ListView

#share post
from .forms import EmailPostForm,CommentForm

from taggit.models import Tag

def post_list(request,tag_slug=None):
  object_list = Post.published.all()
  tag = None
  if tag_slug:
    tag = get_object_or_404(Tag,slug=tag_slug)
    object_list = object_list.filter(tags__in = [tag])
  paginator = Paginator(object_list,3)
  page = request.GET.get('page')
  try:
    posts = paginator.page(page)
  except PageNotAnInteger: #page不是整數，轉到第一頁
    posts = paginator.page(1)
  except EmptyPage:  #page out of range>>deliver to last page
    posts = paginator.page(paginator.num_pages)	
  return render(request,
          'blog/post/list.html',
          {'posts':posts,
          'page':page,
          'tag':tag})

# 展現單獨ㄉ帖子

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published')
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = None
        
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                  'comments': comments, 
                  'new_comment': new_comment,
                  'comment_form': comment_form})

class PostListView(ListView): #類似上面的post_list
	queryset = Post.published.all()
	#查詢集
	context_object_name = 'posts'
	paginate_by = 3 #分頁處理每頁顯示三個對象
	template_name = 'blog/post/list.html'



# from django.http import HttpResponseRedirect
# def redirect_root(request):
# 	return HttpResponseRedirect('/blog/')

Desktop/helen/Program/django_practice/mypage/blog/templates/blog/base.html
{% load blog_tags %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title >{% block title %}{% endblock %}</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/base_style.css' %}">
	<meta charset="utf-8">
</head>
<body>
	<div id="main_title">
		<h1><a href= '{{ post.get_home_page }}' class="button_href">MY BLOG</a></h1>
<!-- 		<a href="#"><img src="{% static 'image/png/login.png' %}" class="icon"></a> -->
	</div>
	<div id='content'>
		{% block content %}
		{% endblock %}
	</div>
	<div id='sidebar'>
		<h3>My Blog</h3>
		<p>I've written {% total_posts %} posts.</p>
		<h4>Latest Post</h4>
			{% show_latest_posts 3 %}
		<h4>Most commented posts</h4>
		{% get_most_commented_posts as most_commented_posts %}
			<ul>
				{% for post in most_commented_posts %}
				<li>
					<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
				</li>
				{% endfor %}
			</ul>
	</div>
</body>
</html>

Desktop/helen/Program/django_practice/mypage/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
	<div id="post_detail" >
		<h1 style="color: #00AAAA">{{ post.title }}</h1>
		<p class="date">
			Published {{ post.publish }} by {{ post.author }}
		</p>
		{{ post.body|linebreaks }}
	</div>
	<hr color="gray" size="5">
<!-- 留言 -->
	<div>
	{% with comments.count as total_comments %}
  	<h2>
    {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
	{% endwith %}
	{% for comment in comments %}
		<div>
			<p>
				Comment {{ forloop.counter}} by {{ comment.name }}
				{{ comment.created }}
			</p>
			{{ comment.body|linebreaks }}
		</div>
	{% empty %}
		<p>There are no comment yet.</p>
	{% endfor %}
	{% if new_comment %}
  		<h3>Your comment has been added.</h3>
	{% else %}
	<hr color="gray" size="5">

	<div>
  		<h2>Add a new comment</h2>
  			<form action="." method="post" style="">
    		{{ comment_form.as_p }}
    		{% csrf_token %}
    		<button type="submit" class="btn btn-outline-secondary">Add comment</button>
  			</form>
  	</div><br><br><br>
	{% endif %}
	

<!-- 	<button type="button" class="btn btn-outline-secondary"><a href= # class="button_href">Add a comment</a></button> -->
	</div>
{% endblock %}

Desktop/helen/Program/django_practice/mypage/blog/templates/blog/post/latest_posts.html
<ul>
	{% for post in latest_posts %}
	<li>
		<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
	</li>
	{% endfor %}
</ul>

Desktop/helen/Program/django_practice/mypage/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}Earth{% endblock %}

{% block content %}
	{% if tag %}
		<h2>Posts tagged with " {{tag.name}} "</h2>
	{% endif %}
	{% for post in posts %}
	<div id="list_post">
		<h2><a href="{{ post.get_absolute_url }}">
			{{ post.title }}
		</a></h2>
		<p class="date">
			Published {{ post.publish }} by {{ post.author }}
		</p>
		{{ post.body|truncatewords:30|linebreaks }}
		<p class="tags">
			Tags:
			{% for tag in post.tags.all %}
				<a href='{% url "blog:post_list_by_tag" tag.slug %}'>
					{{ tag.name }}
				</a> 
				{% if not forloop.last %},{% endif %}
			{% endfor%}
		</p>
	</div>
	<br><br>
	{% endfor %}
	{% include "pagination.html" with page=posts %}
{% endblock %}

Desktop/helen/Program/django_practice/mypage/blog/templates/blog/post/share(廢棄).html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}
	{% if sent %}
		<h1>E-mail successfully sent</h1>
		<p>
			"{{ post.title }}"was successfully sent to {{ cd.to }}
		</p>
	{% else %}
		<h1>Share "{{ post.title }}" by e-mail.</h1>
		<form action="." method="post">
			{{ form.as_p }}
			{% csrf_token %}
			<input type="submit" value="Sent e-mail">
		</form>
	{% endif %}
{% endblock %}

Desktop/helen/Program/django_practice/mypage/blog/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
      {% endif %}
  </span>
</div>    